import type {
  ExportedFunction,
  ExportedModule,
  ExportedParameter,
  ExportedProperty,
  ExportedRecord,
  ExportedSharedObject,
  ExportedSurface,
} from '@expo/expo-modules-macros-plugin';

import { isIdentifier, memberName, parameterName } from './identifiers';
import { renderReturnType, renderType, type RenderContext } from './renderType';

export type RenderWarning = {
  /** Absolute path of the Swift file declaring the member. */
  file: string;
  /** The member in Swift names: `Type.member`, or `Type.function(parameter)` for a parameter. */
  location: string;
  message: string;
};

export type RenderedSurface = {
  /** The declaration file contents, or `null` when the surface exports nothing. */
  source: string | null;
  warnings: RenderWarning[];
};

type ContextFactory = (file: string, location: string) => RenderContext;

/**
 * Tracks the member names emitted into one declaration body. A property must be unique; a function
 * may repeat another function's name (TypeScript reads that as an overload) but not a property's.
 * Static and instance members live in separate namespaces.
 */
class MemberNames {
  private properties = new Set<string>();
  private functions = new Set<string>();

  claimProperty(key: string): boolean {
    if (this.properties.has(key) || this.functions.has(key)) {
      return false;
    }
    this.properties.add(key);
    return true;
  }

  claimFunction(key: string): boolean {
    if (this.properties.has(key)) {
      return false;
    }
    this.functions.add(key);
    return true;
  }
}

function memberTakenWarning(name: string): string {
  return `another member already uses the JS name '${name}', so this one was skipped`;
}

/** The first line of every generated file; identifies files this tool owns. */
export const GENERATED_HEADER_LINE = '// @generated by @expo/modules-cli. Do not edit by hand.';

const HEADER = `${GENERATED_HEADER_LINE}\n// Regenerate with \`expo-modules generate-types\`.\n`;

/**
 * The package that generated files import Expo's own types from. Every Expo module declares `expo`
 * as a peer dependency, while `expo-modules-core` reaches it only transitively.
 */
const EXPO_PACKAGE = 'expo';

/**
 * Swift types provided by `expo-modules-core` that the scanner reports as plain references, with the
 * TypeScript type each converts to and from. A type with `from` is imported from that module; the
 * others are TypeScript globals.
 */
const CORE_TYPES: Record<string, { name: string; from?: string }> = {
  TypedArray: { name: 'TypedArray', from: EXPO_PACKAGE },
  ArrayBuffer: { name: 'ArrayBuffer' },
};

/** The base class of every native module instance on the JS side. */
const NATIVE_MODULE_BASE = { name: 'NativeModule', from: EXPO_PACKAGE };

/** The base class of every shared object instance on the JS side. */
const SHARED_OBJECT_BASE = { name: 'SharedObject', from: EXPO_PACKAGE };

/**
 * Renders a scanned surface as one TypeScript declaration file: records first, then shared
 * objects, then modules, so every declaration precedes the ones that reference it. References to
 * types the `expo` package provides become type-only imports.
 */
export function renderSurface(surface: ExportedSurface): RenderedSurface {
  const warnings: RenderWarning[] = [];

  // A declaration whose TS name is not an identifier, or repeats one already declared in this file,
  // cannot be emitted; it is reported and left out, so references to it resolve as unknown rather
  // than to an invalid or ambiguous declaration.
  const declaredNames = new Set<string>();
  const declarable = <T extends { name: string; file: string }>(
    items: T[],
    tsName: (item: T) => string
  ) =>
    items.filter((item) => {
      const name = tsName(item);
      const problem = !isIdentifier(name)
        ? `'${name}' is not a valid TypeScript identifier, so its declaration was skipped`
        : declaredNames.has(name)
          ? `another declaration already uses the TypeScript name '${name}', so this one was skipped`
          : null;
      if (problem) {
        warnings.push({ file: item.file, location: item.name, message: problem });
        return false;
      }
      declaredNames.add(name);
      return true;
    });
  const records = declarable(surface.records, (record) => record.name);
  const sharedObjects = declarable(surface.sharedObjects, (sharedObject) => sharedObject.jsName);
  const modules = declarable(surface.modules, (module) => module.jsName);

  // Swift type name -> the TS name it is declared under in this file.
  const refs = new Map<string, string>();
  for (const record of records) {
    refs.set(record.name, record.name);
  }
  for (const sharedObject of sharedObjects) {
    refs.set(sharedObject.name, sharedObject.jsName);
  }
  for (const module of modules) {
    refs.set(module.name, module.jsName);
  }

  // Module specifier -> type names to import from it.
  const imports = new Map<string, Set<string>>();
  const addImport = ({ name, from }: { name: string; from: string }) => {
    const names = imports.get(from) ?? new Set<string>();
    names.add(name);
    imports.set(from, names);
  };
  const resolveRef = (name: string): string | undefined => {
    const local = refs.get(name);
    if (local) {
      return local;
    }
    const coreType = CORE_TYPES[name];
    if (coreType?.from) {
      addImport({ name: coreType.name, from: coreType.from });
    }
    return coreType?.name;
  };
  if (modules.length > 0) {
    addImport(NATIVE_MODULE_BASE);
  }
  if (sharedObjects.length > 0) {
    addImport(SHARED_OBJECT_BASE);
  }

  const makeContext: ContextFactory = (file, location) => ({
    resolveRef,
    warn: (message) => {
      warnings.push({ file, location, message });
    },
  });

  const declarations = [
    ...records.map((record) => renderRecord(record, makeContext)),
    ...sharedObjects.map((sharedObject) => renderSharedObject(sharedObject, makeContext)),
    ...modules.map((module) => renderModule(module, makeContext)),
  ];
  if (declarations.length === 0) {
    return { source: null, warnings };
  }
  const importBlock = [...imports.entries()]
    .map(([from, names]) => `import type { ${[...names].sort().join(', ')} } from '${from}';\n`)
    .join('');
  const sections = importBlock ? [HEADER, importBlock, ...declarations] : [HEADER, ...declarations];
  return { source: sections.join('\n'), warnings };
}

function renderRecord(record: ExportedRecord, makeContext: ContextFactory): string {
  const names = new MemberNames();
  const members: string[] = [];
  for (const property of record.properties) {
    const ctx = makeContext(record.file, `${record.name}.${property.name}`);
    if (!names.claimProperty(property.name)) {
      ctx.warn(memberTakenWarning(property.name));
      continue;
    }
    const type = renderType(property.type, ctx);
    members.push(`${memberName(property.name)}${property.required ? '' : '?'}: ${type};`);
  }
  return block(`export type ${record.name} = {`, members, '};');
}

function renderSharedObject(
  sharedObject: ExportedSharedObject,
  makeContext: ContextFactory
): string {
  const members: string[] = [];
  const names = new MemberNames();
  if (sharedObject.constructorParameters) {
    const parameters = renderParameters(
      sharedObject.constructorParameters,
      sharedObject.file,
      `${sharedObject.name}.init`,
      makeContext
    );
    members.push(`constructor(${parameters});`);
  }
  for (const property of sharedObject.properties) {
    const rendered = renderProperty(property, sharedObject, makeContext, names, {
      includeStatic: true,
    });
    if (rendered) {
      members.push(rendered);
    }
  }
  for (const fn of sharedObject.functions) {
    const rendered = renderFunction(fn, sharedObject, makeContext, names, { includeStatic: true });
    if (rendered) {
      members.push(rendered);
    }
  }
  return block(
    `export declare class ${sharedObject.jsName} extends ${SHARED_OBJECT_BASE.name} {`,
    members,
    '}'
  );
}

function renderModule(module: ExportedModule, makeContext: ContextFactory): string {
  // JS only ever sees the module instance that `requireNativeModule` returns, so a member the Swift
  // side declares `static` is still an instance member of that class in TS.
  const names = new MemberNames();
  const members = [
    ...module.properties.map((property) =>
      renderProperty(property, module, makeContext, names, { includeStatic: false })
    ),
    ...module.functions.map((fn) =>
      renderFunction(fn, module, makeContext, names, { includeStatic: false })
    ),
  ].filter((member): member is string => member !== null);
  return block(
    `export declare class ${module.jsName} extends ${NATIVE_MODULE_BASE.name} {`,
    members,
    '}'
  );
}

type Owner = { name: string; file: string };
type MemberOptions = { includeStatic: boolean };

/** Renders one property, or `null` when its name is already taken in the body. */
function renderProperty(
  property: ExportedProperty,
  owner: Owner,
  makeContext: ContextFactory,
  names: MemberNames,
  { includeStatic }: MemberOptions
): string | null {
  const ctx = makeContext(owner.file, `${owner.name}.${property.name}`);
  if (!names.claimProperty(memberKey(property.jsName, includeStatic && property.static))) {
    ctx.warn(memberTakenWarning(property.jsName));
    return null;
  }
  let type: string;
  if (property.type) {
    type = renderType(property.type, ctx);
  } else {
    ctx.warn('type could not be determined from the declaration, rendered as unknown');
    type = 'unknown';
  }
  const modifiers = `${includeStatic && property.static ? 'static ' : ''}${property.readonly ? 'readonly ' : ''}`;
  return `${modifiers}${memberName(property.jsName)}: ${type};`;
}

/** Renders one function, or `null` when a property already owns its name in the body. */
function renderFunction(
  fn: ExportedFunction,
  owner: Owner,
  makeContext: ContextFactory,
  names: MemberNames,
  { includeStatic }: MemberOptions
): string | null {
  const location = `${owner.name}.${fn.name}`;
  if (!names.claimFunction(memberKey(fn.jsName, includeStatic && fn.static))) {
    makeContext(owner.file, location).warn(memberTakenWarning(fn.jsName));
    return null;
  }
  const parameters = renderParameters(fn.parameters, owner.file, location, makeContext);
  const returns = renderReturnType(fn.returns, fn.async, makeContext(owner.file, `${location}()`));
  return `${includeStatic && fn.static ? 'static ' : ''}${memberName(fn.jsName)}(${parameters}): ${returns};`;
}

function renderParameters(
  parameters: ExportedParameter[],
  file: string,
  location: string,
  makeContext: ContextFactory
): string {
  const lastRequiredIndex = parameters.findLastIndex((parameter) => !parameter.optional);
  return parameters
    .map((parameter, index) => {
      const name = parameterName(parameter.name, index);
      const type = renderType(parameter.type, makeContext(file, `${location}(${name})`));
      if (!parameter.optional) {
        return `${name}: ${type}`;
      }
      // TypeScript only allows optional parameters at the end of the list. Swift allows a defaulted
      // parameter before a required one, so such a parameter accepts `undefined` explicitly instead.
      return index < lastRequiredIndex ? `${name}: ${type} | undefined` : `${name}?: ${type}`;
    })
    .join(', ');
}

/** The namespace-qualified key a member occupies in its body. */
function memberKey(jsName: string, isStatic: boolean): string {
  return isStatic ? `static ${jsName}` : jsName;
}

/** Lays out a declaration body with two-space indentation and a trailing newline. */
function block(open: string, members: string[], close: string): string {
  if (members.length === 0) {
    return `${open}${close}\n`;
  }
  return `${open}\n${members.map((member) => `  ${member}`).join('\n')}\n${close}\n`;
}
